import streamlit as st
import pandas as pd
import time
import random

# Page Config
st.set_page_config(page_title="AnalyticsEngine", layout="wide")

st.title("📊 AnalyticsEngine: Column-Oriented Store")
st.subheader("Simulating Big Data Analytics with Column Families")

# Step A: Initialize Column Families in session state
if 'user_data' not in st.session_state:
    # Simulating independent column files as per the concept
    st.session_state.user_data = {"id": [1, 2], "name": ["Alex", "Sarah"]}
    st.session_state.geo_data = {"id": [1, 2], "city": ["Madrid", "Barcelona"]}
    st.session_state.metrics_data = {"id": [1, 2], "ad_spend": [500, 300], "clicks": [120, 85]}

# Sidebar for Mass Ingestion (Step B)
with st.sidebar:
    st.header("📥 Ingest New Record")
    with st.form("ingest_form"):
        new_name = st.text_input("Name")
        new_city = st.text_input("City")
        new_spend = st.number_input("Ad Spend", min_value=0)
        new_clicks = st.number_input("Clicks", min_value=0)
        submit = st.form_submit_button("Insert to All Families")
        
        if submit:
            new_id = len(st.session_state.user_data["id"]) + 1
            # In Column-oriented, we write to 3 "independent files" simultaneously
            st.session_state.user_data["id"].append(new_id)
            st.session_state.user_data["name"].append(new_name)
            st.session_state.geo_data["id"].append(new_id)
            st.session_state.geo_data["city"].append(new_city)
            st.session_state.metrics_data["id"].append(new_id)
            st.session_state.metrics_data["ad_spend"].append(new_spend)
            st.session_state.metrics_data["clicks"].append(new_clicks)
            st.success(f"Record {new_id} added to all Column Families!")

# Create Tabs
tab1, tab2 = st.tabs(["🔍 Column Query", "📈 Analytics Dashboard"])

# Step B: Selective Queries and I/O
with tab1:
    st.header("Selective Column Scan")
    all_columns = ["id", "name", "city", "ad_spend", "clicks"]
    selected_cols = st.multiselect("Select columns to read (Simulate selective I/O):", all_columns, default=["id"])
    
    if st.button("Execute Selective Read"):
        start_time = time.time()
        
        # Simulating that we only join the "files" we need
        result_df = pd.DataFrame({"id": st.session_state.user_data["id"]})
        
        for col in selected_cols:
            if col == "name": result_df["name"] = st.session_state.user_data["name"]
            if col == "city": result_df["city"] = st.session_state.geo_data["city"]
            if col == "ad_spend": result_df["ad_spend"] = st.session_state.metrics_data["ad_spend"]
            if col == "clicks": result_df["clicks"] = st.session_state.metrics_data["clicks"]
            
        end_time = time.time()
        processing_ms = (end_time - start_time) * 1000
        
        st.dataframe(result_df)
        
        # Analytics Insight
        cols_ignored = len(all_columns) - len(selected_cols)
        st.info(f"⏱️ Processing time: {processing_ms:.4f} ms")
        st.warning(f"🛡️ Bandwidth saved: {cols_ignored} columns ignored. The system did NOT read those files.")

# Step C: Analytical Dashboard
with tab2:
    st.header("Big Data Aggregation")
    
    # Merge only necessary columns: city and ad_spend (skipping name, clicks, etc.)
    df_analytics = pd.DataFrame({
        "City": st.session_state.geo_data["city"],
        "Ad_Spend": st.session_state.metrics_data["ad_spend"]
    })
    
    chart_data = df_analytics.groupby("City")["Ad_Spend"].sum()
    st.bar_chart(chart_data)
    
    st.write("💡 **Engineering Note:** This chart was generated by scanning ONLY the 'City' and 'Ad_Spend' columns. "
             "The 'Name' and 'Clicks' columns were completely ignored, making it 50% more efficient than a Row-based scan.")
